# SPDX-FileCopyrightText: 2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

# These are supported funding model platforms
custom:
  - "https://etherscan.io/address/0xD653E9c96910D44923027bB0365Ca4A8f580894F"
  - "https://www.blockchain.com/btc/address/bc1qx58y00ljpz0e2anpq90f6uztf0puyuvnq4pcvf"
  - "https://www.dial.to/?action=solana-action:https://action.solscan.io/api/donate?receiver=GJacUwSi5w9KU8u4fC7XYWYhi6yU6m4dCvmDRmFTbs4R"
