# Homebrew formula for the twc-rs prebuilt binaries.
#
# Place this file in a tap repository (github.com/RAprogramm/homebrew-tap) as
# Formula/twc-rs.rb so users can run:  brew install RAprogramm/tap/twc-rs
#
# The sha256 values below are placeholders. After cutting a release, fill them
# with the per-asset checksums published next to each tarball (the .sha256
# files generated by the release workflow).
class TwcRs < Formula
  desc "Fast CLI and interactive TUI dashboard for managing Timeweb Cloud"
  homepage "https://github.com/RAprogramm/twc-rs"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/RAprogramm/twc-rs/releases/download/v#{version}/twc-rs-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/RAprogramm/twc-rs/releases/download/v#{version}/twc-rs-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/RAprogramm/twc-rs/releases/download/v#{version}/twc-rs-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/RAprogramm/twc-rs/releases/download/v#{version}/twc-rs-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "twc-rs"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/twc-rs --version")
  end
end
